#! /usr/bin/env bash

# create tar file for uploading atableau package to ctan

CTANIFY="/Library/TeX/texbin/ctanify"

TAR=$(tar --version)
GTAR=$(tar --version)

if [[ "$TAR" != "$GTAR" ]]
then
  # use gnu-tar because tar on macosx adds spurious system files
  echo "WARNING: tar is not gnu-tar!"
fi

# create the tar file for ctan
$CTANIFY --no-tds atableau.{ini,sty,pdf,tex} {CHANGES,README,TODO}.md LICENSE

# remind user to check version number and the copyright and release dates
echo "Check version, release date and the copyright years in atableau.sty"
ag --nonumbers "@(release|version)" atableau.sty  | ag def
ag --nonumbers "copyright" atableau.sty
ag --nonumbers "(version|date|copyright)\s=" atableau.ini
